# Generated by Django 4.2.4 on 2023-09-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('credito', models.PositiveIntegerField()),
                ('periodo', models.PositiveIntegerField()),
                ('interdependencias', models.ManyToManyField(blank=True, related_name='interdependente_de', to='myapp.materias')),
            ],
        ),
    ]
