# Generated by Django 4.2.4 on 2023-10-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='materias',
            name='periodo',
        ),
        migrations.AddField(
            model_name='materias',
            name='codependencias',
            field=models.ManyToManyField(blank=True, related_name='codependente_de', to='myapp.materias'),
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('materias', models.ManyToManyField(blank=True, related_name='curso_de', through='myapp.CursoMateria', to='myapp.materias')),
            ],
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cursos'),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.materias'),
        ),
        migrations.AlterUniqueTogether(
            name='cursomateria',
            unique_together={('curso', 'materia')},
        ),
    ]
