# Generated by Django 4.2.4 on 2023-10-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cursomateria_remove_materias_periodo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('materias', models.ManyToManyField(blank=True, related_name='optativa_de', to='myapp.materias')),
            ],
        ),
        migrations.CreateModel(
            name='CursoOptativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cursos')),
                ('optativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.optativas')),
            ],
            options={
                'unique_together': {('curso', 'optativa')},
            },
        ),
        migrations.AddField(
            model_name='cursos',
            name='optativas',
            field=models.ManyToManyField(blank=True, related_name='curso_de', through='myapp.CursoOptativa', to='myapp.optativas'),
        ),
    ]
