# Generated by Django 4.2.4 on 2023-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_optativas_cursooptativa_cursos_optativas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='codependencias',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='interdependencias',
        ),
        migrations.AlterField(
            model_name='cursos',
            name='optativas',
            field=models.ManyToManyField(blank=True, related_name='optativa_de', through='myapp.CursoOptativa', to='myapp.optativas'),
        ),
        migrations.CreateModel(
            name='InterdependenciaGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materias', models.ManyToManyField(related_name='interdependencia_grupos', to='myapp.materias')),
            ],
        ),
        migrations.CreateModel(
            name='CodependenciaGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materias', models.ManyToManyField(related_name='codependencia_grupos', to='myapp.materias')),
            ],
        ),
    ]
