# Generated by Django 4.2.4 on 2023-10-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_materias_codependencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='codependencias',
            field=models.ManyToManyField(blank=True, related_name='materias_codependencias', to='myapp.codependenciagrupos'),
        ),
        migrations.AddField(
            model_name='materias',
            name='interdependencias',
            field=models.ManyToManyField(blank=True, related_name='materias_interdependencias', to='myapp.interdependenciagrupos'),
        ),
    ]
