# Generated by Django 4.2.4 on 2023-10-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_materias_codependencias_materias_interdependencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='optativas',
            name='codigo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
